# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Jahwa/windows/vivado/pynq_mb/jahwa_daq_system/jahwa_daq_system.srcs/sources_1/bd/jahwa_daq_system/ip/jahwa_daq_system_ilmb_0_0_1/jahwa_daq_system_ilmb_0_0.xci
# IP: The module: 'jahwa_daq_system_ilmb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Jahwa/windows/vivado/pynq_mb/jahwa_daq_system/jahwa_daq_system.gen/sources_1/bd/jahwa_daq_system/ip/jahwa_daq_system_ilmb_0_0_1/jahwa_daq_system_ilmb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jahwa_daq_system_ilmb_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Jahwa/windows/vivado/pynq_mb/jahwa_daq_system/jahwa_daq_system.srcs/sources_1/bd/jahwa_daq_system/ip/jahwa_daq_system_ilmb_0_0_1/jahwa_daq_system_ilmb_0_0.xci
# IP: The module: 'jahwa_daq_system_ilmb_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Jahwa/windows/vivado/pynq_mb/jahwa_daq_system/jahwa_daq_system.gen/sources_1/bd/jahwa_daq_system/ip/jahwa_daq_system_ilmb_0_0_1/jahwa_daq_system_ilmb_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jahwa_daq_system_ilmb_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
