# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Jahwa/windows/vivado/constraint_file/pynq_z1.xdc

# Block Designs: bd/jahwa_daq_system/jahwa_daq_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system || ORIG_REF_NAME==jahwa_daq_system} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_processing_system7_0_0_1/jahwa_daq_system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_processing_system7_0_0 || ORIG_REF_NAME==jahwa_daq_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_intc_0_0_1/jahwa_daq_system_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_intc_0_0 || ORIG_REF_NAME==jahwa_daq_system_axi_intc_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_iic_0_0_1/jahwa_daq_system_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_iic_0_0 || ORIG_REF_NAME==jahwa_daq_system_axi_iic_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_quad_spi_0_0_1/jahwa_daq_system_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_quad_spi_0_0 || ORIG_REF_NAME==jahwa_daq_system_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_gpio_0_0_1/jahwa_daq_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_gpio_0_0 || ORIG_REF_NAME==jahwa_daq_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_gpio_1_0_1/jahwa_daq_system_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_gpio_1_0 || ORIG_REF_NAME==jahwa_daq_system_axi_gpio_1_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_gpio_2_0_1/jahwa_daq_system_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_gpio_2_0 || ORIG_REF_NAME==jahwa_daq_system_axi_gpio_2_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_gpio_3_0_1/jahwa_daq_system_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_gpio_3_0 || ORIG_REF_NAME==jahwa_daq_system_axi_gpio_3_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_gpio_4_0_1/jahwa_daq_system_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_gpio_4_0 || ORIG_REF_NAME==jahwa_daq_system_axi_gpio_4_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_gpio_5_0/jahwa_daq_system_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_gpio_5_0 || ORIG_REF_NAME==jahwa_daq_system_axi_gpio_5_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_clock_divider_0_0_1/jahwa_daq_system_axi_clock_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_clock_divider_0_0 || ORIG_REF_NAME==jahwa_daq_system_axi_clock_divider_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_xbar_0_1/jahwa_daq_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_xbar_0 || ORIG_REF_NAME==jahwa_daq_system_xbar_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_auto_pc_1_1/jahwa_daq_system_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_auto_pc_1 || ORIG_REF_NAME==jahwa_daq_system_auto_pc_1} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_auto_pc_0_1/jahwa_daq_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_auto_pc_0 || ORIG_REF_NAME==jahwa_daq_system_auto_pc_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_interconnect_0_0_1/jahwa_daq_system_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_interconnect_0_0 || ORIG_REF_NAME==jahwa_daq_system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_xlslice_0_0_1/jahwa_daq_system_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_xlslice_0_0 || ORIG_REF_NAME==jahwa_daq_system_xlslice_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_xlslice_1_0_1/jahwa_daq_system_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_xlslice_1_0 || ORIG_REF_NAME==jahwa_daq_system_xlslice_1_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_bram_ctrl_0_0_1/jahwa_daq_system_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==jahwa_daq_system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_gpio_0_1_1/jahwa_daq_system_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_gpio_0_1 || ORIG_REF_NAME==jahwa_daq_system_axi_gpio_0_1} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_timer_0_0_1/jahwa_daq_system_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_timer_0_0 || ORIG_REF_NAME==jahwa_daq_system_axi_timer_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_timer_1_0_1/jahwa_daq_system_axi_timer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_timer_1_0 || ORIG_REF_NAME==jahwa_daq_system_axi_timer_1_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_timer_2_0_1/jahwa_daq_system_axi_timer_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_timer_2_0 || ORIG_REF_NAME==jahwa_daq_system_axi_timer_2_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_xlconcat_0_0_1/jahwa_daq_system_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_xlconcat_0_0 || ORIG_REF_NAME==jahwa_daq_system_xlconcat_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_intc_0_1_1/jahwa_daq_system_axi_intc_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_intc_0_1 || ORIG_REF_NAME==jahwa_daq_system_axi_intc_0_1} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_xbar_1_1/jahwa_daq_system_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_xbar_1 || ORIG_REF_NAME==jahwa_daq_system_xbar_1} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_axi_interconnect_0_1_1/jahwa_daq_system_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_axi_interconnect_0_1 || ORIG_REF_NAME==jahwa_daq_system_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_dff_en_reset_vector_0_0_1/jahwa_daq_system_dff_en_reset_vector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_dff_en_reset_vector_0_0 || ORIG_REF_NAME==jahwa_daq_system_dff_en_reset_vector_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_mdm_0_0_1/jahwa_daq_system_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_mdm_0_0 || ORIG_REF_NAME==jahwa_daq_system_mdm_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_microblaze_0_0_1/jahwa_daq_system_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_microblaze_0_0 || ORIG_REF_NAME==jahwa_daq_system_microblaze_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_rst_ps7_0_100M_0_1/jahwa_daq_system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==jahwa_daq_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_xlconstant_0_0_1/jahwa_daq_system_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_xlconstant_0_0 || ORIG_REF_NAME==jahwa_daq_system_xlconstant_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_dlmb_0_0_1/jahwa_daq_system_dlmb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_dlmb_0_0 || ORIG_REF_NAME==jahwa_daq_system_dlmb_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_ilmb_0_0_1/jahwa_daq_system_ilmb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_ilmb_0_0 || ORIG_REF_NAME==jahwa_daq_system_ilmb_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_ilmb_bram_ctrl_0_0_1/jahwa_daq_system_ilmb_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_ilmb_bram_ctrl_0_0 || ORIG_REF_NAME==jahwa_daq_system_ilmb_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/jahwa_daq_system/ip/jahwa_daq_system_lmb_bram_0_0_1/jahwa_daq_system_lmb_bram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jahwa_daq_system_lmb_bram_0_0 || ORIG_REF_NAME==jahwa_daq_system_lmb_bram_0_0} -quiet] -quiet

# XDC: d:/Jahwa/windows/vivado/pynq_mb/jahwa_daq_system/jahwa_daq_system.gen/sources_1/bd/jahwa_daq_system/jahwa_daq_system_ooc.xdc
